# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: get short sha
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build linux-amd64
      run: env GOOS=linux GOARCH=amd64 go build -o system-data-exporter_linux_amd64

    - name: Build linux-arm64
      run: env GOOS=linux GOARCH=arm64 go build -o system-data-exporter_linux_arm64

    - name: Build windows-amd64
      run: env GOOS=win GOARCH=amd64 go build -o system-data-exporter_win_amd64

    - name: release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./system-data-exporter_linux_amd64
        tag: ${{ steps.vars.outputs.sha_short }}

    - name: release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./system-data-exporter_linux_arm64
        tag: ${{ steps.vars.outputs.sha_short }}

    - name: release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./system-data-exporter_win_amd64
        tag: ${{ steps.vars.outputs.sha_short }}
