# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: get short sha
      id: vars1
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: get commit-date
      id: vars2
      run: echo "git_date=$(git log -1 --format=%cd)" >> $GITHUB_OUTPUT

    - name: Build linux-amd64
      run: env GOOS=linux GOARCH=amd64 go build -ldflags="-s -X 'main.git_commit_hash=${{ steps.vars1.outputs.sha_short }}' -X 'main.git_commit_date=${{ steps.vars2.outputs.git_date }}'" -o system-data-exporter_linux_amd64

    - name: Build linux-arm64
      run: env GOOS=linux GOARCH=arm64 go build -ldflags="-s -X 'main.git_commit_hash=${{ steps.vars1.outputs.sha_short }}' -X 'main.git_commit_date=${{ steps.vars2.outputs.git_date }}'" -o system-data-exporter_linux_arm64

    - name: Build win-amd64
      run: env GOOS=windows GOARCH=amd64 go build -ldflags="-s -X 'main.git_commit_hash=${{ steps.vars1.outputs.sha_short }}' -X 'main.git_commit_date=${{ steps.vars2.outputs.git_date }}'" -o system-data-exporter_win_amd64.exe

    - name: release linux-amd64
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./system-data-exporter_linux_amd64
        tag: ${{ steps.vars1.outputs.sha_short }}

    - name: release linux-arm64
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./system-data-exporter_linux_arm64
        tag: ${{ steps.vars1.outputs.sha_short }}

    - name: release win-amd64
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./system-data-exporter_win_amd64.exe
        tag: ${{ steps.vars1.outputs.sha_short }}

    - name: run system-data-exporter
      run: chmod 0777 ./system-data-exporter_linux_amd64 && ./system-data-exporter_linux_amd64
